stages:
  - lint
  - test
  - e2e-test


lint:
  image: node:latest
  stage: lint
  before_script:
    - cd bulb
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y \
      eslint-plugin-prettier \
      eslint-plugin-react
  script:
    - node_modules/eslint/bin/eslint.js .

unit-test:
  image: node:latest
  stage: test
  before_script:
    - cd bulb
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/





test:
  # Uses official Cypress docker image for dependencies
  # https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  script:
    - set -o pipefail
    - yes | true
    
