stages:
  - lint
  - test


lint:
  image: node:latest
  stage: lint
  before_script:
    - cd bulb
    - npm i eslint
  script:
    - node_modules/eslint/bin/eslint.js .

unit-test:
  image: node:latest
  stage: test
  before_script:
    - cd bulb
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
