stages:
  - lint
  - test
  - e2e-test


lint:
  image: node:latest
  stage: lint
  before_script:
    - cd bulb
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y \
      eslint-plugin-prettier \
      eslint-plugin-react
  script:
    - node_modules/eslint/bin/eslint.js .

unit-test:
  image: node:latest
  stage: test
  before_script:
    - cd bulb
    - npm ci
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/


e2e-test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: e2e-test
  before_script:
    - cd bulb
    - npm ci
  script:
    # start the server in the background
    - npm run e2e:headless