import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bulb platform",
	description: "Generated by create next app",
};
 
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const show = false;
	return (

		<html lang="en">
			<body className={inter.className}>

					<Providers>
						<div className="flex">

							<Sidebar />
							{children}
						</div>
					</Providers>

			</body>
		</html>

	);
}
