import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bulb platform",
	description: "Generated by create next app",
};
 
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const show = false;
	return (

		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<div className="flex bg-primaryGrey">
						<Navbar />
						{children}
					</div>
				</Providers>

			</body>
		</html>

	);
}
