import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from "./providers";
import { getServerSession } from "next-auth";

import SessionProvider from "./components/SessionProvider";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bulb platform",
	description: "Generated by create next app",
};
 
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();


	const show = false;
	return (

		<html lang="en">
			<body className={inter.className}>
				<SessionProvider basePath="http://localhost:3000/api/auth" session={session}>

					<Providers>
						<div className="flex">

							<Sidebar />
							{children}
						</div>
					</Providers>
				</SessionProvider>
			</body>
		</html>

	);
}
